package lab2.pcg.deck.enums;

public enum Expansion {
	
	// This list of expansions was created by copying the entire table from
	// https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_Trading_Card_Game_expansions
	// as text and regex-ing it to the correct java syntax.
	// For the sake of archiving, here are the find-replace expressions:
	//.*\.png \t(?:— \t)?(.*?) \t.* \t(.*)
	//\t\2\(\"\1\"\),
	
	BS("Base Set"),
	JU("Jungle"),
	FO("Fossil"),
	B2("Base Set 2"),
	TR("Team Rocket"),
	G1("Gym Heroes"),
	G2("Gym Challenge"),
	N1("Neo Genesis"),
	N2("Neo Discovery"),
	N3("Neo Revelation"),
	N4("Neo Destiny"),
	LC("Legendary Collection"),
	EX("Expedition Base Set"),
	AQ("Aquapolis"),
	SK("Skyridge"),
	RS("EX Ruby & Sapphire"),
	SS("EX Sandstorm"),
	DR("EX Dragon"),
	MA("EX Team Magma vs Team Aqua"),
	HL("EX Hidden Legends"),
	FL("EX FireRed & LeafGreen"),
	TRR("EX Team Rocket Returns"),
	DX("EX Deoxys"),
	EM("EX Emerald"),
	UF("EX Unseen Forces"),
	DS("EX Delta Species"),
	LM("EX Legend Maker"),
	HP("EX Holon Phantoms"),
	CG("EX Crystal Guardians"),
	DF("EX Dragon Frontiers"),
	PK("EX Power Keepers"),
	DP("Diamond & Pearl"),
	MT("Mysterious Treasures"),
	SW("Secret Wonders"),
	GE("Great Encounters"),
	MD("Majestic Dawn"),
	LA("Legends Awakened"),
	SF("Stormfront"),
	PL("Platinum"),
	RR("Rising Rivals"),
	SV("Supreme Victors"),
	AR("Arceus"),
	HS("HeartGold & SoulSilver"),
	UL("Unleashed"),
	UD("Undaunted"),
	TM("Triumphant"),
	CL("Call of Legends"),
	BLW("Black & White"),
	EPO("Emerging Powers"),
	NVI("Noble Victories"),
	NXD("Next Destinies"),
	DEX("Dark Explorers"),
	DRX("Dragons Exalted"),
	BCR("Boundaries Crossed"),
	PLS("Plasma Storm"),
	PLF("Plasma Freeze"),
	PLB("Plasma Blast"),
	LTR("Legendary Treasures"),
	XY("XY"),
	FLF("Flashfire"),
	FFI("Furious Fists"),
	PHF("Phantom Forces"),
	PRC("Primal Clash"),
	ROS("Roaring Skies"),
	AOR("Ancient Origins"),
	BKT("BREAKthrough"),
	BKP("BREAKpoint"),
	FCO("Fates Collide"),
	STS("Steam Siege"),
	EVO("Evolutions"),
	SUM("Sun & Moon"),
	GRI("Guardians Rising"),
	BUS("Burning Shadows"),
	CIN("Crimson Invasion"),
	UPR("Ultra Prism"),
	FLI("Forbidden Light"),
	CES("Celestial Storm"),
	LOT("Lost Thunder"),
	TEU("Team Up"),
	UNB("Unbroken Bonds"),
	UNM("Unified Minds"),
	CEC("Cosmic Eclipse"),
	SSH("Sword & Shield"),
	RCL("Rebel Clash"),
	DAA("Darkness Ablaze"),
	VIV("Vivid Voltage");
	
	public final String displayName;
	
	Expansion(String displayName) {
		this.displayName = displayName;
	}

}
